name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          user: fujatyping
          plugin_activity: yes
          plugin_activity_limit: 5
          
          plugin_languages: yes
          plugin_languages_indepth: yes
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          
          plugin_anilist: yes
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 12
          
