name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          user: fujatyping
          plugin_activity: yes
          plugin_activity_limit: 3

          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 10
        
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Bangkok
          
          plugin_languages: yes
          plugin_languages_indepth: yes
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          
